main:
  timezone: Europe/Kiev
  max_bytes_limit: 5e+7
  temp_dir_name: ds_reports  # will be created in your system temp folder unless "directory" is specified
#  directory: /Users/Optima/Projects/ds_reports/data # use this for a specific folder

sign_api:
  sign_file_url: http://localhost:6543/sign/file
  username: test
  password: test

es:
  host: http://10.6.4.227:9200
  index: hpi-sandbox-*

swift:
  auth_version: 3
  os_username: os_username
  os_password: os_password
  os_user_domain_name: default
  os_project_name: os_project_name
  os_project_domain_name: default
  os_auth_url: https://swift/v3
  temp_url_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  insecure: True
  object_uu_threads: 20
  container_prefix: doc-report-dev

email:
  smtp_server: mail.dc.prozorro.gov.ua
  smtp_port: 25
  verified_email: blablabla@prozorro.ua
  use_tls: false
  use_auth: false
  username: ""
  password: ""


brokers_emails:
  test.quintagroup.com: blablav@gmail.com
  netcast.com.ua:
    - blablav@gmail.com
    - whatisit@gmail.com

logging:
  version: 1
  formatters:
    default:
      class: logging.Formatter
      format: "%(asctime)s %(levelname)-8s %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
  loggers:
    "":
      handlers: [console]
      level: INFO
    DocReportsLogger:
      handlers: [console]
      propagate: no
      level: INFO